SULACHHEN KARMACHARYA
KCE080BCT041

In [18]:
#supressing warning = it sis just a warning to run a code smoothly
import warnings
warnings.filterwarnings('ignore')

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("synthetic_sales_data.csv")
df

,Transaction_ID,Date,Customer_ID,Customer_Name,Customer_Gender,Customer_Region,Category,Price,Discount_Amount,Quantity,Payment_Method,Store_Location,Online/Offline,Product_Rating
0,T000001,2024-07-19,C1006,Robert Perry,Female,WST,Clothing,516.14,NaN,5.0,Debit Card,Store A,Online,1.0
1,T000002,2023-09-17,C1492,Kenneth Huang,Female,WST,electronic,NaN,10.11,10.0,Credit Card,Store D,Offline,1.6
2,T000003,2024-03-31,C1153,Juan Hatfield,Female,South,Grocery,772.67,6.63,1.0,Online Payment,Store A,NaN,3.8
3,T000004,2023-05-22,C1029,NaN,Male,East,Electronics,241.14,8.55,2.0,Debit Card,Store D,Offline,NaN
4,NaN,2023-03-05,C1115,Emily Pruitt,Female,south,Clothing,968.59,11.18,4.0,Credit Card,Store B,Offline,2.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,T000996,2024-09-29,C1316,Edward Mcdonald,Female,North,electronic,958.53,5.53,5.0,Debit Card,Store A,Online,1.6
996,T000997,2024-02-04,C1485,Taylor Hughes,Male,Est,Furnitures,446.94,0.90,3.0,Cash,Store B,Offline,2.9
997,NaN,2024-05-08,C1418,Emily Morrison,Male,East,NaN,NaN,NaN,8.0,Cash,Store A,Offline,NaN
998,T000999,2023-06-12,C1350,Denise Wagner,Male,West,Furniture,291.12,4.46,3.0,Cash,Store C,Offline,2.3
999,T001000,2024-05-05,C1123,Scott Martin,Male,East,Electronics,39.19,10.04,1.0,Online Payment,NaN,Online,NaN

In [20]:
#checking how many features and observations are there
df.shape

(1000, 14)

In [21]:
df.isnull().sum()

Transaction_ID      75
Date                59
 Customer_ID        92
Customer_Name       88
Customer_Gender     69
Customer_Region     81
Category            63
Price               86
Discount_Amount    269
Quantity            89
Payment_Method      62
Store_Location      94
Online/Offline      80
 Product_Rating    180
dtype: int64

In [22]:
#renaming the feature that having white space
df.columns=df.columns.str.strip()
df.isnull().sum()

Transaction_ID      75
Date                59
Customer_ID         92
Customer_Name       88
Customer_Gender     69
Customer_Region     81
Category            63
Price               86
Discount_Amount    269
Quantity            89
Payment_Method      62
Store_Location      94
Online/Offline      80
Product_Rating     180
dtype: int64

In [23]:
#removing the data that doesn't have customerId,customerName,transactionId
df.dropna(subset=['Transaction_ID','Customer_ID','Customer_Name','Date'],inplace=True)
df

,Transaction_ID,Date,Customer_ID,Customer_Name,Customer_Gender,Customer_Region,Category,Price,Discount_Amount,Quantity,Payment_Method,Store_Location,Online/Offline,Product_Rating
0,T000001,2024-07-19,C1006,Robert Perry,Female,WST,Clothing,516.14,NaN,5.0,Debit Card,Store A,Online,1.0
1,T000002,2023-09-17,C1492,Kenneth Huang,Female,WST,electronic,NaN,10.11,10.0,Credit Card,Store D,Offline,1.6
2,T000003,2024-03-31,C1153,Juan Hatfield,Female,South,Grocery,772.67,6.63,1.0,Online Payment,Store A,NaN,3.8
5,T000006,2024-01-21,C1280,Tiffany Smith,Female,South,Grocery,562.81,4.39,6.0,Cash,Store A,Online,4.5
6,T000007,2023-08-16,C1294,Heather Holmes,Female,NaN,ELECTRONIC,447.44,4.68,9.0,Online Payment,Store A,Offline,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,T000995,2023-07-28,C1294,Curtis Phillips,Male,East,Furniture,949.81,11.82,2.0,Debit Card,Store B,Online,1.1
995,T000996,2024-09-29,C1316,Edward Mcdonald,Female,North,electronic,958.53,5.53,5.0,Debit Card,Store A,Online,1.6
996,T000997,2024-02-04,C1485,Taylor Hughes,Male,Est,Furnitures,446.94,0.90,3.0,Cash,Store B,Offline,2.9
998,T000999,2023-06-12,C1350,Denise Wagner,Male,West,Furniture,291.12,4.46,3.0,Cash,Store C,Offline,2.3
999,T001000,2024-05-05,C1123,Scott Martin,Male,East,Electronics,39.19,10.04,1.0,Online Payment,NaN,Online,NaN

In [24]:
#checking if observations has dropeed or not
df.shape

(725, 14)

In [25]:
#asking for the file info
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 725 entries, 0 to 999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction_ID   725 non-null    object
 1   Date             725 non-null    object
 2   Customer_ID      725 non-null    object
 3   Customer_Name    725 non-null    object
 4   Customer_Gender  681 non-null    object
 5   Customer_Region  666 non-null    object
 6   Category         681 non-null    object
 7   Price            659 non-null    float64
 8   Discount_Amount  531 non-null    float64
 9   Quantity         659 non-null    float64
 10  Payment_Method   679 non-null    object
 11  Store_Location   661 non-null    object
 12  Online/Offline   668 non-null    object
 13  Product_Rating   596 non-null    float64
dtypes: float64(4), object(10)
memory usage: 85.0+ KB

In [26]:
#again checking null value of the feature
df.isnull().sum()

Transaction_ID       0
Date                 0
Customer_ID          0
Customer_Name        0
Customer_Gender     44
Customer_Region     59
Category            44
Price               66
Discount_Amount    194
Quantity            66
Payment_Method      46
Store_Location      64
Online/Offline      57
Product_Rating     129
dtype: int64

In [31]:
#for null value in gender replacing with not specified
df['Customer_Gender']=df['Customer_Gender'].fillna("Not Specified")
df['Customer_Region']=df['Customer_Region'].fillna("Not Specified")
df['Discount_Amount']=df['Discount_Amount'].fillna(0)
df['Store_Location']=df['Store_Location'].fillna("Not Specified")
df['Product_Rating']=df['Product_Rating'].fillna("Not Rated")

mode_category=df['Category'].mode()[0]
print(f"Mode for category:{mode_category}")
df['Category']=df['Category'].fillna(mode_category)


median_price=df['Price'].median()
print(f"Median for price:{median_price}")
df['Price']=df['Price'].fillna(median_price)


mode_quantity=df['Quantity'].mode()[0]
print(f"Mode for quantity:{mode_quantity}")
df['Quantity']=df['Quantity'].fillna(mode_quantity)


mode_payment=df['Payment_Method'].mode()[0]
print(f"Mode for payment method:{mode_payment}")
df['Payment_Method']=df['Payment_Method'].fillna(mode_payment)


mode_online=df['Online/Offline'].mode()[0]
print(f"Mode for online/offline:{mode_online}")
df['Online/Offline']=df['Online/Offline'].fillna(mode_online)


median_productrating = df['Category'].median()
print(f"Median for product rating :{median_productrating}")
df['Price']=df['Price'].fillna(median_productrating)

df

Mode for category:Clothing
Median for price:490.65
Mode for quantity:1.0
Mode for payment method:Credit Card
Mode for online/offline:Offline

TypeError: Cannot convert ['Clothing' 'electronic' 'Grocery' 'Grocery' 'ELECTRONIC' 'electronic'
 'Electronics' 'Clothing' 'Furnitures' 'Clothing' 'Furniture' 'Furniture'
 'Furnitures' 'Grocery' 'Grocery' 'ELECTRONIC' 'Clothing' 'Furniture'
 'Clothing' 'electronic' 'Grocery' 'Grocery' 'Clothing' 'Grocery'
 'Furniture' 'Furniture' 'Clothing' 'Clothing' 'Furnitures' 'Electronics'
 'Grocery' 'Furniture' 'ELECTRONIC' 'Electronics' 'Furniture' 'Clothing'
 'electronic' 'Furniture' 'Furniture' 'Grocery' 'ELECTRONIC' 'ELECTRONIC'
 'Clothing' 'Grocery' 'electronic' 'Clothing' 'Furnitures' 'Grocery'
 'Clothing' 'Furnitures' 'Furnitures' 'Grocery' 'Furnitures' 'electronic'
 'ELECTRONIC' 'Clothing' 'Clothing' 'Furniture' 'Furnitures' 'electronic'
 'Grocery' 'Furniture' 'Furniture' 'electronic' 'Clothing' 'Clothing'
 'Furnitures' 'Furnitures' 'Furnitures' 'Furniture' 'Grocery' 'electronic'
 'Furnitures' 'Furnitures' 'Furniture' 'Electronics' 'Furnitures'
 'Grocery' 'Electronics' 'Clothing' 'Grocery' 'Furniture' 'electronic'
 'Electronics' 'Clothing' 'Furniture' 'Electronics' 'Furnitures'
 'Furniture' 'Clothing' 'Furnitures' 'Clothing' 'Clothing' 'Clothing'
 'Electronics' 'Clothing' 'Clothing' 'ELECTRONIC' 'ELECTRONIC'
 'ELECTRONIC' 'Electronics' 'ELECTRONIC' 'electronic' 'Clothing'
 'electronic' 'Grocery' 'Electronics' 'Electronics' 'Furniture'
 'Furnitures' 'electronic' 'Grocery' 'Clothing' 'ELECTRONIC' 'electronic'
 'Electronics' 'Furniture' 'Furniture' 'Electronics' 'Electronics'
 'ELECTRONIC' 'Clothing' 'Grocery' 'ELECTRONIC' 'Furniture' 'electronic'
 'Grocery' 'ELECTRONIC' 'Clothing' 'Electronics' 'Clothing' 'electronic'
 'Electronics' 'Grocery' 'Furniture' 'Clothing' 'Electronics' 'Clothing'
 'Furniture' 'Furnitures' 'ELECTRONIC' 'Grocery' 'Furniture' 'electronic'
 'Furniture' 'ELECTRONIC' 'Furniture' 'Furniture' 'Furnitures'
 'Furnitures' 'Clothing' 'electronic' 'Clothing' 'Furniture' 'Clothing'
 'Clothing' 'Furniture' 'Furniture' 'Furnitures' 'Grocery' 'Electronics'
 'Grocery' 'Electronics' 'Furnitures' 'Furnitures' 'Furnitures' 'Clothing'
 'Clothing' 'Clothing' 'Grocery' 'electronic' 'electronic' 'ELECTRONIC'
 'ELECTRONIC' 'ELECTRONIC' 'electronic' 'electronic' 'Electronics'
 'Electronics' 'Grocery' 'ELECTRONIC' 'electronic' 'Furnitures'
 'Electronics' 'Electronics' 'Electronics' 'Clothing' 'electronic'
 'electronic' 'electronic' 'Clothing' 'electronic' 'ELECTRONIC' 'Clothing'
 'Electronics' 'Clothing' 'Grocery' 'Electronics' 'Clothing' 'Grocery'
 'Furnitures' 'Clothing' 'Electronics' 'Clothing' 'Electronics'
 'Electronics' 'Clothing' 'Clothing' 'ELECTRONIC' 'ELECTRONIC'
 'Furnitures' 'electronic' 'electronic' 'Clothing' 'Furnitures'
 'electronic' 'Furnitures' 'Grocery' 'Furniture' 'Furnitures' 'electronic'
 'ELECTRONIC' 'Furnitures' 'Clothing' 'Furnitures' 'electronic'
 'Electronics' 'Electronics' 'ELECTRONIC' 'ELECTRONIC' 'ELECTRONIC'
 'Furnitures' 'Furnitures' 'Grocery' 'Clothing' 'Furnitures' 'Clothing'
 'Grocery' 'electronic' 'Clothing' 'ELECTRONIC' 'Clothing' 'electronic'
 'Furniture' 'Clothing' 'electronic' 'Clothing' 'electronic' 'Clothing'
 'Furniture' 'Furniture' 'Clothing' 'Clothing' 'electronic' 'Electronics'
 'Grocery' 'Clothing' 'Grocery' 'Furnitures' 'Furniture' 'Clothing'
 'Furnitures' 'Clothing' 'Clothing' 'ELECTRONIC' 'Electronics'
 'electronic' 'Furnitures' 'Electronics' 'Electronics' 'Grocery'
 'Furniture' 'Furnitures' 'ELECTRONIC' 'Clothing' 'Furnitures'
 'ELECTRONIC' 'Clothing' 'electronic' 'Grocery' 'Furnitures' 'Grocery'
 'electronic' 'Clothing' 'Clothing' 'Clothing' 'Clothing' 'electronic'
 'Furniture' 'Grocery' 'electronic' 'Furniture' 'Clothing' 'electronic'
 'electronic' 'Furniture' 'Furnitures' 'electronic' 'ELECTRONIC'
 'ELECTRONIC' 'Clothing' 'ELECTRONIC' 'ELECTRONIC' 'ELECTRONIC'
 'Furniture' 'Furniture' 'ELECTRONIC' 'Furnitures' 'Furnitures'
 'ELECTRONIC' 'ELECTRONIC' 'Furnitures' 'Electronics' 'Furniture'
 'Clothing' 'Clothing' 'Furniture' 'ELECTRONIC' 'Grocery' 'Electronics'
 'ELECTRONIC' 'Furniture' 'Furnitures' 'Furnitures' 'Clothing'
 'Furnitures' 'Furniture' 'ELECTRONIC' 'Clothing' 'Clothing' 'electronic'
 'Furniture' 'Furnitures' 'Furnitures' 'Clothing' 'Furniture' 'electronic'
 'ELECTRONIC' 'Electronics' 'Grocery' 'Furniture' 'Furniture' 'Furniture'
 'Clothing' 'Grocery' 'Furniture' 'Electronics' 'Electronics' 'ELECTRONIC'
 'Furniture' 'Grocery' 'Furnitures' 'Furniture' 'electronic' 'Electronics'
 'Electronics' 'Furnitures' 'Furnitures' 'Electronics' 'Grocery' 'Grocery'
 'Electronics' 'Clothing' 'Grocery' 'Electronics' 'ELECTRONIC'
 'ELECTRONIC' 'Grocery' 'Furnitures' 'electronic' 'Furniture' 'Furniture'
 'Electronics' 'Clothing' 'Furniture' 'electronic' 'ELECTRONIC'
 'ELECTRONIC' 'Furniture' 'Clothing' 'Furnitures' 'Furnitures' 'Grocery'
 'Grocery' 'electronic' 'Furnitures' 'Clothing' 'Furnitures' 'Clothing'
 'Electronics' 'ELECTRONIC' 'Furnitures' 'Electronics' 'Grocery'
 'Furnitures' 'Clothing' 'Electronics' 'Clothing' 'Furnitures'
 'ELECTRONIC' 'Clothing' 'Clothing' 'Furnitures' 'Furnitures' 'Grocery'
 'Furniture' 'ELECTRONIC' 'Furniture' 'Clothing' 'Clothing' 'Furniture'
 'Clothing' 'electronic' 'Furnitures' 'Grocery' 'Electronics' 'Furniture'
 'Grocery' 'Furniture' 'Furniture' 'Furniture' 'ELECTRONIC' 'Grocery'
 'Grocery' 'Grocery' 'Furniture' 'Furnitures' 'ELECTRONIC' 'electronic'
 'Furnitures' 'Furniture' 'Clothing' 'Clothing' 'Grocery' 'Clothing'
 'Furniture' 'Furniture' 'Grocery' 'Furnitures' 'Clothing' 'Furnitures'
 'Grocery' 'Furniture' 'electronic' 'Grocery' 'Clothing' 'Furniture'
 'Clothing' 'Grocery' 'ELECTRONIC' 'Furnitures' 'ELECTRONIC' 'Clothing'
 'Furnitures' 'ELECTRONIC' 'Grocery' 'Clothing' 'Electronics'
 'Electronics' 'Electronics' 'Grocery' 'Electronics' 'Electronics'
 'Grocery' 'Grocery' 'Electronics' 'electronic' 'Grocery' 'Electronics'
 'Clothing' 'Furnitures' 'Clothing' 'Clothing' 'Furniture' 'Furnitures'
 'Electronics' 'electronic' 'Electronics' 'Furniture' 'Grocery' 'Clothing'
 'Clothing' 'Electronics' 'Clothing' 'Furniture' 'Grocery' 'Furniture'
 'Clothing' 'Electronics' 'Clothing' 'Clothing' 'Grocery' 'Electronics'
 'Electronics' 'Furniture' 'Furnitures' 'ELECTRONIC' 'Electronics'
 'Furniture' 'Furniture' 'Grocery' 'ELECTRONIC' 'Clothing' 'electronic'
 'Grocery' 'Electronics' 'Clothing' 'Clothing' 'Electronics' 'Clothing'
 'ELECTRONIC' 'Furniture' 'Clothing' 'Electronics' 'Clothing' 'Furniture'
 'Clothing' 'electronic' 'Furnitures' 'Grocery' 'Clothing' 'electronic'
 'electronic' 'Furnitures' 'Grocery' 'Grocery' 'Furnitures' 'Electronics'
 'ELECTRONIC' 'ELECTRONIC' 'electronic' 'electronic' 'electronic'
 'Furnitures' 'Grocery' 'Clothing' 'Grocery' 'electronic' 'electronic'
 'Clothing' 'Furnitures' 'Electronics' 'Furniture' 'ELECTRONIC'
 'Electronics' 'Electronics' 'Clothing' 'ELECTRONIC' 'Electronics'
 'Furnitures' 'electronic' 'Electronics' 'Furnitures' 'Grocery'
 'Electronics' 'Clothing' 'Clothing' 'Furnitures' 'Electronics'
 'electronic' 'Grocery' 'Clothing' 'Furniture' 'Clothing' 'Clothing'
 'Furniture' 'Clothing' 'Clothing' 'ELECTRONIC' 'Furniture' 'Grocery'
 'electronic' 'Clothing' 'Furnitures' 'Clothing' 'ELECTRONIC' 'Clothing'
 'Electronics' 'Clothing' 'Clothing' 'ELECTRONIC' 'Furnitures' 'Grocery'
 'Clothing' 'Furniture' 'ELECTRONIC' 'Clothing' 'ELECTRONIC' 'Clothing'
 'Clothing' 'Clothing' 'Furnitures' 'electronic' 'ELECTRONIC' 'Grocery'
 'electronic' 'ELECTRONIC' 'Electronics' 'electronic' 'Clothing'
 'Clothing' 'Furniture' 'Furnitures' 'electronic' 'Clothing' 'Grocery'
 'Grocery' 'Grocery' 'Grocery' 'Furnitures' 'electronic' 'Clothing'
 'ELECTRONIC' 'ELECTRONIC' 'electronic' 'ELECTRONIC' 'Electronics'
 'Furniture' 'Grocery' 'Grocery' 'Grocery' 'ELECTRONIC' 'Grocery'
 'ELECTRONIC' 'ELECTRONIC' 'Furnitures' 'Electronics' 'ELECTRONIC'
 'Furnitures' 'Clothing' 'Furnitures' 'Grocery' 'Electronics' 'Furniture'
 'Clothing' 'electronic' 'Furniture' 'Electronics' 'Clothing' 'Clothing'
 'electronic' 'Clothing' 'Grocery' 'Electronics' 'electronic' 'ELECTRONIC'
 'ELECTRONIC' 'Furnitures' 'Grocery' 'ELECTRONIC' 'Furnitures' 'Furniture'
 'electronic' 'Furniture' 'Furniture' 'Electronics' 'Furnitures'
 'Clothing' 'Clothing' 'Electronics' 'Furniture' 'electronic' 'ELECTRONIC'
 'Clothing' 'Furniture' 'electronic' 'Furniture' 'ELECTRONIC' 'ELECTRONIC'
 'Electronics' 'Clothing' 'Clothing' 'Clothing' 'Electronics'
 'Electronics' 'Grocery' 'Furnitures' 'Clothing' 'Electronics' 'Clothing'
 'Clothing' 'Clothing' 'Furnitures' 'Electronics' 'Clothing' 'Grocery'
 'electronic' 'Clothing' 'Electronics' 'ELECTRONIC' 'Furnitures' 'Grocery'
 'Grocery' 'Grocery' 'Clothing' 'Clothing' 'Clothing' 'Grocery'
 'ELECTRONIC' 'Electronics' 'electronic' 'Clothing' 'Grocery' 'Furnitures'
 'ELECTRONIC' 'Clothing' 'Grocery' 'Electronics' 'ELECTRONIC'
 'Electronics' 'Furniture' 'Furnitures' 'Grocery' 'Clothing' 'Electronics'
 'Grocery' 'Furniture' 'Electronics' 'Grocery' 'Grocery' 'Furniture'
 'electronic' 'Furnitures' 'Furniture' 'Electronics'] to numeric

In [ ]:
#checking datatypes of feastures
df.dtypes

In [ ]:
#converting into suitable datatypes
df['Date']=pd.to_datetime(df['Date'])
df['Quantity']=df['Quantity'].astype(int)
df.dtypes

In [ ]:
#checking number of unique value for different features
df.nunique()

In [ ]:
#euta data lai different type le lekheko xa ki xna check gareko
df['Category'].unique()

In [ ]:
#replacing category with only one unique category
df['Category']=df['Category'].replace({'Furniture':'Furnitures','electronic':'Electronics','ELECTRONIC':'Electronics'})
df

In [ ]:
#euta data lai different type le lekheko xa ki xna check gareko
df['Customer_Region'].unique()
df['Customer_Region']=df['Customer_Region'].replace({'WST':'West','Est':'EAST','NORTH':'North','south':'South','EAST':'East','WEST':'West'})
df['Customer_Region'].unique()

In [ ]:
#euta data lai different type le lekheko xa ki xna check gareko
df['Store_Location'].unique()

In [ ]:
#calculating total amount
df['Total_Amount']=(df['Price'] * df['Quantity']) - df['Discount_Amount']
df

In [ ]:
#calculating discount percentage
df['Discount_Percentage']=(df['Discount_Amount']/(df['Price'] * df['Quantity'])) * 100
df['Discount_Percentage']=df['Discount_Percentage'].round(2)
df

In [ ]:
#adding new feature CLV(Customer Lifetime Value)
customerID_counts=df['Customer_ID'].value_counts()
print(customerID_counts)

In [ ]:
#aggregate transactions by Customer_ID
clv_df = df.groupby('Customer_ID')['Total_Amount'].sum().reset_index()
clv_df.rename(columns={'Total_Amount': 'CLV'}, inplace=True)

#normalize CLV using min-max scaling to rate from 0 t0 10
min_clv = clv_df['CLV'].min()
max_clv = clv_df['CLV'].max()
clv_df['CLV_Scaled'] = ((clv_df['CLV'] - min_clv) / (max_clv - min_clv)) * 10

print(clv_df)

In [ ]:
#EDA Starts 

#calculating average spend for each customer in each category(tspc = total spend per customer, aspc = average spend per customer)
tspc_category = df.groupby(['Customer_ID', 'Category'])['Total_Amount'].sum().reset_index()
aspc_category = tspc_category.groupby(['Customer_ID', 'Category'])['Total_Amount'].mean().reset_index()
print(aspc_category)

In [ ]:
#calculating frequency of purchase 

#counting the number of transactiond for each customer_id and store_lovation
purchase_freq = df.groupby(['Customer_ID', 'Store_Location']).size().reset_index(name='Frequency')
print(purchase_freq)

In [ ]:
##preferred payment method 

#dentifying the most frequently used payment method for each customer( pp = preferred payment)

pp_method = df.groupby('Customer_ID')['Payment_Method'].agg(lambda x: x.mode()[0]).reset_index()
print(pp_method)

In [ ]:
##online/offline preference

#determining the percentage of online vs offline purchases for each customer
onoff_preference = df.groupby(['Customer_ID', 'Online/Offline']).size().unstack(fill_value=0)
onoff_preference_percentage = onoff_preference.div(onoff_preference.sum(axis=1), axis=0) * 100
print(onoff_preference_percentage)

In [ ]:
##product pupularity

#counting the number of times each Product_Type is purchased and rank them.
prod_popularity= df['Category'].value_counts().reset_index(name='Purchase_Count')
prod_popularity = prod_popularity.sort_values(by='Purchase_Count', ascending=False)
prod_popularity['Rank'] = np.arange(1, len(prod_popularity)+1)
print(prod_popularity)

In [ ]:
##Data visualization starts here


#list of numeric features
numeric_features = ['Price', 'Discount_Amount', 'Quantity', 'Total_Amount', 'Product_Rating']

#skewness
print("Skewness for each numeric feature:")
for feature in numeric_features:
    print(f"{feature}: {skew(df[feature].dropna())}")

#correlation matrix
correlation_matrix = df[numeric_features].corr()

#displaying the correlation matrix
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Correlation Matrix')
plt.show()

In [ ]:
# Plotting histograms for visual skewness check
plt.figure(figsize=(10, 8))
for i, feature in enumerate(numeric_features, 1):
    plt.subplot(2, 3, i)
    sns.histplot(df[feature], kde=True)
    plt.title(f"Distribution of {feature}")
plt.tight_layout()
plt.show()

In [ ]:
# List of categorical features (add the names of your categorical columns)
categorical_features = ['Category', 'Customer_Gender', 'Payment_Method', 'Store_Location', 'Online/Offline']  # Modify as per your data

# Plotting count plots for categorical features
plt.figure(figsize=(10, 8))
for i, feature in enumerate(categorical_features, 1):
    plt.subplot(2, 3, i)
    sns.countplot(x=df[feature])
    plt.title(f"Distribution of {feature}")
plt.tight_layout()
plt.show()